# Java_練習問題22

---

## 例外

---

### 練習問題①

```java

public class ExceptionPractice01 {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc");
        } catch (NumberFormatException e) {
            System.out.println("NumberFormatException Integer.parseInt \"abc\"");
        }
        try {
            Integer.parseInt("def");
        } catch (NumberFormatException e) {
            System.out.println("NumberFormatException Integer.parseInt \"def\"");
        }
    }
}

```

---

### 練習問題②

```java

public class ExceptionPractice02 extends Exception {

    public ExceptionPractice02() {
        super();
    }

    public ExceptionPractice02(Throwable th) {
        super(th);
    }
}

```

```java

public class Test02 {
    public static void throwException() throws ExceptionPractice02 {
        throw new ExceptionPractice02();
    }

    public static void main(String[] args) {
        try {
            throwException();
        } catch (ExceptionPractice02 e) {
            System.out.println(e.getClass().getSuperclass());
        }
    }
}

```

---

### 練習問題③

```java
public class ExceptionPractice03 extends RuntimeException {

    public ExceptionPractice03() {
        super();
    }

    public ExceptionPractice03(Throwable th) {
        super(th);
    }
}
```

```java
public class Test03 {
    public static void throwException() {
        throw new ExceptionPractice03();
    }

    public static void main(String[] args) {
        try {
            throwException();
        } catch (ExceptionPractice03 e) {
            System.out.println(e.getClass().getSuperclass());
        }
    }
}
```

---

### 練習問題④

```java
public class ExceptionPractice04 {
    public static void main(String[] args) {
        try {
            Integer.parseInt(args[0]);
        } catch (NullPointerException | NumberFormatException | ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }
}
```
