# Java_練習問題22

---

## 例外

---

### 練習問題①

以下のプログラムを実行すると例外が発生する。

```java
public class ExceptionPractice01 {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc"); // ①
            Integer.parseInt("def"); // ②
        } catch (NumberFormatException e) {
            System.out.println("NumberFormatException");
        }
    }
}
```

しかし、①、②のどちらで例外が発生しているのか判断できない。
実行した結果、以下のように出力されるようにtry-catchを2つに分けて、修正しなさい。

* ①で例外が発生した場合、以下のように出力
  * NumberFormatException Integer.parseInt "abc"
* ②で例外が発生した場合、以下のように出力
  * NumberFormatException Integer.parseInt "def"

---

### 練習問題②

以下のTest02クラスがある。

```java
public class Test02 {
    public static void throwException() throws ExceptionPractice02 {
        throw new ExceptionPractice02();
    }
    public static void main(String[] args) {
        try {
            throwException();
        } catch (ExceptionPractice02 e) {
            System.out.println(e.getClass().getSuperclass());
        }
    }
}
```

Test02クラスで使用しているExceptionPractice02クラスを作成しなさい。
ただし、ExceptionPractice02クラスは次ページの条件を満たすものとする。

条件

* チェック例外であること
* 引数なしのコンストラクターを持っていること
* 引数なしのコンストラクターは親クラスの引数なしのコンストラクターを呼び出していること
* Throwable型の引数を一つ持つコンストラクターを持っていること
* Throwable型の引数を一つ持つコンストラクターは親クラスのThrowable型を引数を一つ持つコンストラクターを呼び出していること

---

### 練習問題③

以下のTest03クラスがある。

```java
public class Test03 {
    public static void throwException() {
        throw new ExceptionPractice03();
    }
    public static void main(String[] args) {
        try {
            throwException();
        } catch (ExceptionPractice03 e) {
            System.out.println(e.getClass().getSuperclass());
        }
    }
}
```

Test03クラスで使用しているExceptionPractice03クラスを作成しなさい。
ただし、 ExceptionPractice03クラスは次ページの条件を満たすものとする。

条件

* Test03クラスは変更せずにコンパイルが通ること
* 引数なしのコンストラクターを持っていること
* 引数なしのコンストラクターは親クラスの引数なしのコンストラクターを呼び出していること
* Throwable型の引数を一つ持つコンストラクターを持っていること
* Throwable型の引数を一つ持つコンストラクターは親クラスのThrowable型を引数を一つ持つコンストラクターを呼び出していること

---

### 練習問題④

以下のプログラムは三つの例外処理で同じ処理を行っている。
Java7で追加されたマルチキャッチを利用して処理をまとめなさい。

```java
public class ExceptionPractice04 {
    public static void main(String[] args) {
        try {
            Integer.parseInt(args[0]);
        } catch (NullPointerException e) {
            e.printStackTrace();
        } catch (NumberFormatException e) {
            e.printStackTrace();
        } catch (ArrayIndexOutOfBoundsException e) { 
            e.printStackTrace();
        }
    }
}
```
